"""Generate NOV08-X golden vectors for the Rust validator from the verified Python nov08x chain.

    python validator-rs/tools/gen_nov08_vectors.py

Writes validator-rs/tests/data/nov08_data.rs — the deployed NOV08-X genesis (leading-zero-bits PoW,
COIN=1e6, 100-coin subsidy, `==` coinbase rule) plus a few mined blocks, each with its hash / merkle
/ leading-zero-bits pow_ok, so `cargo test` cross-checks the Rust node's NOV08 consensus byte-for-byte
against the Python. Mines at MINPROOFOFWORK (20 leading-zero bits): a few seconds per block. NOT money.
"""
import pathlib
import sys

D = pathlib.Path(__file__).resolve().parents[2]  # tools/ -> validator-rs/ -> derivatives/
for p in ("model", "p2p", "nov08x", "netnode"):
    sys.path.insert(0, str(D / p))

from chainsync import block_hash                       # noqa: E402
from p2p import block_bytes, merkle_root               # noqa: E402
from tx_sighash import Tx, TxIn, TxOut                  # noqa: E402
from chains import CHAINS                               # noqa: E402

cfg = CHAINS["nov08x"]
R = cfg.rules
ZERO = b"\x00" * 32
NBITS = R.min_pow            # leading-zero bits; the floor for heights below the retarget interval
_tag = [0]


def coinbase(height, value, spk=b"\x51"):
    _tag[0] += 1
    s = bytes([height & 0xFF, (height >> 8) & 0xFF, _tag[0] & 0xFF, (_tag[0] >> 8) & 0xFF])
    return Tx(1, [TxIn(ZERO, 0xFFFFFFFF, s, 0xFFFFFFFF)], [TxOut(value, spk)], 0)


def mine(prev, height, nbits, txs):
    mr = merkle_root(txs)
    t = 1226793600 + height * 30
    for nonce in range(1 << 24):
        raw = block_bytes(1, prev, mr, t, nbits, nonce, txs)
        if R.pow_ok(block_hash(raw), nbits):
            return raw
    raise RuntimeError("no nonce found")


def ntx_of(raw):
    n = raw[80]
    assert n < 0xFD                       # all our blocks are coinbase-only
    return n


g = cfg.mint_genesis()                    # the deployed NOV08-X genesis (00000f08...)
rows = [(g, 0)]
prev = block_hash(g)
for h in range(1, 4):
    value = R.get_block_value(h - 1)      # NOV08 100-coin subsidy — exactly what the connect check wants
    raw = mine(prev, h, NBITS, [coinbase(h, value)])
    rows.append((raw, h))
    prev = block_hash(raw)

out = ["// generated by gen_nov08_vectors.py from the verified Python nov08x — do not edit", ""]
out.append("pub const MAGIC: [u8; 4] = [0x%02x, 0x%02x, 0x%02x, 0x%02x];" % tuple(cfg.magic))
out.append('pub const GENESIS: &str = "%s";' % g.hex())
out.append("")
out.append("// (raw_hex, height, nbits, block_hash, merkle_root, pow_ok_leading_zero_bits, ntx)")
out.append("pub const CHAIN: &[(&str, i64, u32, &str, &str, bool, u64)] = &[")
for raw, h in rows:
    nb = int.from_bytes(raw[72:76], "little")
    bh = block_hash(raw).hex()
    mr = raw[36:68].hex()
    pk = R.pow_ok(block_hash(raw), nb)
    out.append('    ("%s", %d, %d, "%s", "%s", %s, %d),'
               % (raw.hex(), h, nb, bh, mr, "true" if pk else "false", ntx_of(raw)))
out.append("];")
out.append("")

dst = D / "validator-rs" / "tests" / "data" / "nov08_data.rs"
dst.write_text("\n".join(out), encoding="utf-8")
print("wrote", dst)
print("genesis:", block_hash(g).hex(), "nbits:", int.from_bytes(g[72:76], "little"),
      "leading-zero-bits pow_ok:", R.pow_ok(block_hash(g), NBITS))
for raw, h in rows[1:]:
    print("  block", h, block_hash(raw).hex()[:16], "pow_ok:", R.pow_ok(block_hash(raw), NBITS),
          "value:", R.get_block_value(h - 1))
