"""Regenerate a CHECKMULTISIG golden vector (a real 2-of-2 bare-multisig spend) from the verified
Python model. Writes validator-rs/tests/data/multisig_data.rs. NOT money."""
import pathlib
import sys

D = pathlib.Path(__file__).resolve().parents[2]
for p in ("model", "p2p", "nov08x"):
    sys.path.insert(0, str(D / p))

import cscript
from tx_sighash import Tx, TxIn, TxOut, new_key, serialize as ser_tx
from spend import sign, verify_spend

priv1, pub1 = new_key()
priv2, pub2 = new_key()
wrong, _ = new_key()

spk_tokens = ["OP_2", pub1, pub2, "OP_2", "OP_CHECKMULTISIG"]   # bare 2-of-2 multisig
spk = cscript.assemble(spk_tokens)
prev = b"\x11" * 32


def build(sig_keys):
    tx = Tx(1, [TxIn(prev, 0, b"", 0xFFFFFFFF)], [TxOut(1000, b"\x51")], 0)
    sigs = [sign(k, spk_tokens, tx, 0) for k in sig_keys]          # signed over the multisig scriptCode
    script_sig_tokens = ["OP_0", *sigs]                            # OP_0 = the CHECKMULTISIG off-by-one dummy
    script_sig = cscript.assemble(script_sig_tokens)
    tx.vin[0].script = script_sig
    ok = verify_spend(script_sig_tokens, spk_tokens, tx, 0)         # ground truth from the model
    return ser_tx(tx).hex(), script_sig.hex(), ok


good_tx, good_ss, good_ok = build([priv1, priv2])                  # correct order -> valid
bad_tx, bad_ss, bad_ok = build([priv1, wrong])                     # second sig wrong -> invalid
assert good_ok and not bad_ok, (good_ok, bad_ok)

out = ["// generated by gen_multisig_vectors.py from the verified Python model — do not edit", ""]
out.append("// (label, tx_hex, spk_hex, script_sig_hex, expected)")
out.append("pub const MULTISIG: &[(&str, &str, &str, &str, bool)] = &[")
out.append(f'    ("good_2of2", "{good_tx}", "{spk.hex()}", "{good_ss}", true),')
out.append(f'    ("bad_2of2", "{bad_tx}", "{spk.hex()}", "{bad_ss}", false),')
out.append("];")
out.append("")

dst = D / "validator-rs" / "tests" / "data" / "multisig_data.rs"
dst.write_text("\n".join(out), encoding="utf-8")
print("wrote", dst, "good_ok=", good_ok, "bad_ok=", bad_ok)
