#!/usr/bin/env python3
"""Assemble paper.md from paper.template.md + the engine's generated tables. NOT money.

⛔⛔ paper.md IS A BUILD ARTIFACT. DO NOT EDIT IT. Edit paper.template.md.

WHY THIS EXISTS
-----------------
Two referee rounds found the same class of defect over and over: the manuscript quoted numbers the
engine computes, they were maintained by hand, and they drifted apart. **My repairs then introduced
six further regressions** — a figure showing 18 rows under a caption saying 17, a minus sign that
pdfTeX silently dropped, three literal BEL bytes from a `\\a` in a replacement string.

  ★★★ NONE OF THAT WAS CARELESSNESS. It is the predicted output of keeping the authority (the
      engine) and the presentation (the manuscript) in separate documents and reconciling them by
      hand. **The fix is structural: generate, do not transcribe.**

HOW IT WORKS
--------------
`paper.template.md` contains placeholders:

    {{TABLE:table2_rates}}     -> the contents of tables/table2_rates.md
    {{FIG:rate_BSV}}           -> a scalar from tables/figures.json

Every number the prose quotes must come through `{{FIG:...}}`. **A literal digit in the template is
a bug waiting to happen**, and `check_template.py` (below) reports any that look like results.

Run:  python build_paper.py           # writes paper.md
      python build_paper.py --check   # fails if paper.md is stale or hand-edited
"""
import hashlib
import io
import json
import re
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
HERE = Path(__file__).resolve().parent
TPL = HERE / "paper.template.md"
OUT = HERE / "paper.md"
TABLES = HERE / "tables"

RX_TABLE = re.compile(r"\{\{TABLE:([a-z0-9_]+)\}\}")
RX_FIG = re.compile(r"\{\{FIG:([a-zA-Z0-9_]+)\}\}")
STAMP = "<!-- GENERATED by build_paper.py from paper.template.md -- DO NOT EDIT -- %s -->"


def build():
    if not TPL.exists():
        print("  paper.template.md not found — nothing to build")
        return 2
    figs = json.loads((TABLES / "figures.json").read_text(encoding="utf-8"))
    body = TPL.read_text(encoding="utf-8")

    missing = []

    def table(m):
        p = TABLES / (m.group(1) + ".md")
        if not p.exists():
            missing.append("table:" + m.group(1))
            return m.group(0)
        return p.read_text(encoding="utf-8").rstrip("\n")

    def fig(m):
        k = m.group(1)
        if k not in figs:
            missing.append("fig:" + k)
            return m.group(0)
        return str(figs[k])

    body = RX_TABLE.sub(table, body)
    body = RX_FIG.sub(fig, body)

    if missing:
        print("  ⛔ UNRESOLVED PLACEHOLDERS — refusing to write a paper with holes in it:")
        for k in sorted(set(missing)):
            print("       %s" % k)
        return 1

    # ⚠️ ASCII-ONLY GUARD. A previous repair introduced U+2212 (pdfTeX drops it silently) and three
    #    BEL bytes. Anything outside ASCII except the em dash is refused at build time.
    bad = sorted({c for c in body if ord(c) > 126 and c != "—"})
    if bad:
        print("  ⛔ NON-ASCII IN OUTPUT — these have silently corrupted the PDF before:")
        for c in bad:
            print("       U+%04X %r  x%d" % (ord(c), c, body.count(c)))
        return 1

    # ⛔ THE GUARD ABOVE WAS NOT ENOUGH, AND THE WAY IT FAILED IS THE POINT.
    #    Forbidding U+2212 did not remove the bad minus — it sent the engine back to `$-$`, the
    #    ORIGINAL broken form, which is pure ASCII and sailed through. **A guard that bans one
    #    spelling of a defect selects for the others.** So ban the shape, not the character:
    #    pandoc will not close a math span immediately before a digit, so `$…$<digit>` renders
    #    literally. This catches `$-$0.0392` in any table the engine emits, now or later.
    traps = re.findall(r"\$[^$\n]{0,12}\$\d", body)
    if traps:
        print("  ⛔ MATH SPAN IMMEDIATELY BEFORE A DIGIT — this renders literally in the PDF:")
        for t in sorted(set(traps)):
            print("       %r  x%d" % (t, body.count(t)))
        print("     use a plain ASCII '-' in table cells; no math span is needed there.")
        return 1

    # ⛔ CAPTION<->TABLE BINDING, added 14 Aug 2026 (R3) and the finding that forced it:
    #    this builder already REFUSED to write a paper with a MISSING table. Nothing checked that
    #    the table it inserted was the one the caption promised — so all five placeholders were
    #    shifted by one, table3_provenance was generated and inserted nowhere, and two tables ran
    #    with no caption at all, and every gate stayed green.
    #    ★★★ THE VACUOUS-CHECK PATTERN ONE LEVEL UP: a check on PRESENCE reads as a check on
    #    CORRECTNESS until something is present and wrong.
    ct = HERE / "check_template.py"
    if ct.exists():
        import subprocess
        r = subprocess.run([sys.executable, str(ct)], capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        if r.returncode != 0:
            print("  ⛔ check_template.py refuses this template:\n")
            print(r.stdout.rstrip())
            return 1
        print("  check_template.py: clean")
    # ★ R5: check_claims.py asserts ENTAILMENTS -- sentences true of the old dataset and false of
    #   the new one, with no number for check_template to compare. That is the class that survived
    #   five rounds of numeric gates.
    cc = HERE / "check_claims.py"
    if cc.exists():
        r = subprocess.run([sys.executable, str(cc)], capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        if r.returncode != 0:
            print("  ⛔ check_claims.py: the manuscript asserts something the data no longer "
                  "supports\n")
            print(r.stdout.rstrip())
            return 1
        print("  check_claims.py: clean")
    else:
        print("  ⚠ check_claims.py absent — ENTAILMENTS are UNCHECKED")

    h = hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]
    OUT.write_text(body + "\n" + (STAMP % h) + "\n", encoding="utf-8", newline="\n")
    print("  built paper.md  (%d bytes, template sha %s)" % (len(body), h))
    return 0


def check():
    """Fail if paper.md was hand-edited or is older than its inputs."""
    if not OUT.exists():
        print("  paper.md missing"); return 1
    cur = OUT.read_text(encoding="utf-8")
    m = re.search(r"template sha ([0-9a-f]{16})|DO NOT EDIT -- ([0-9a-f]{16})", cur)
    if not m:
        print("  ⛔ paper.md carries no generation stamp — it was hand-written or hand-edited.")
        return 1
    stamped = m.group(1) or m.group(2)
    body = cur.rsplit("<!--", 1)[0].rstrip("\n")
    actual = hashlib.sha256((body + "\n").encode("utf-8")).hexdigest()[:16]
    ok = stamped == actual
    print("  stamp %s vs recomputed %s  %s" % (stamped, actual, "OK" if ok else "⛔ EDITED"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv else build())
