//! Stateful validator tests: connect a real signed chain (tracking the UTXO count + balance) and
//! reject rule-violating blocks — all cross-checked against the verified Python `ChainState`.
//! The golden data (`state_data.rs`) is generated by `gen_state_vectors.py`. NOT money.

use obl_validator::chainstate::ChainState;

include!("data/state_data.rs");

fn hexd(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn valid_chain_connects_and_tracks_the_utxo() {
    let mut st = ChainState::new(MATURITY, STRICT);
    for (raw, height, subsidy, is_genesis, utxo_count, balance) in VALID {
        st.connect_block(&hexd(raw), *height, *subsidy, *is_genesis)
            .expect("valid block should connect");
        assert_eq!(st.utxo_count(), *utxo_count, "utxo count at height {height}");
        assert_eq!(st.balance(), *balance, "balance at height {height}");
    }
}

#[test]
fn value_and_script_rules_reject_invalid_blocks() {
    let mut st = ChainState::new(MATURITY, STRICT);
    for (raw, height, subsidy, is_genesis, _uc, _bal) in VALID {
        st.connect_block(&hexd(raw), *height, *subsidy, *is_genesis).unwrap();
    }
    // each invalid block violates exactly one rule; the exact reason must match the Python node,
    // and an atomic connect must leave the UTXO unchanged after a rejection.
    for (name, raw, height, subsidy, expected_err) in INVALID {
        let before = (st.utxo_count(), st.balance());
        let got = st.connect_block(&hexd(raw), *height, *subsidy, false);
        assert_eq!(got, Err(*expected_err), "case {name}");
        assert_eq!((st.utxo_count(), st.balance()), before, "state unchanged after {name}");
    }
}
