#!/usr/bin/env python3
"""One-command reproducer for the JAN09 edition's executable layer.

Runs every headless derivatives test suite, and regenerates the derived artifacts (the neutral
descendant matrix, the NOV08-X differential, the two laboratory genesis blocks) to prove they
reproduce from source. Python only by default — no build step. Pass --rust to also run the Rust
node's `cargo test` suite, and/or --cpp to run the C++/OpenSSL port differentials (which include the
historical January genesis re-derivation, node_port.cpp).

    python scripts/reproduce.py            # all Python suites + regenerate artifacts
    python scripts/reproduce.py --rust     # + the Rust node suite (needs cargo)
    python scripts/reproduce.py --cpp      # + the C++ port differentials (needs g++ and OpenSSL headers)
    python scripts/reproduce.py --strict   # a suite that only skipped, or a reference implementation
                                           # that is not installed, FAILS instead of being reported

Three states per step, and the difference matters:

    PASS   tests ran and passed
    SKIP   pytest exited 0 because every test skipped (a reference implementation is not installed);
           nothing was checked. Counted as green only without --strict, and always shown as SKIP
    FAIL   a test failed, or a regenerated artifact differs from the committed bytes

A regenerated artifact is compared to the committed bytes and the committed bytes are restored
whether or not they match, so a run leaves the working tree as it found it; a mismatch is a FAIL
with the diff stat printed. (An earlier version of this script checked only the regenerator's exit
code and left the rewritten artifact in the tree; three outside reviewers reported a green run that
had flipped every row of the conformance matrix. Both defects are the reason for this design.)

The manifest (--manifest, implied by --core) records per step: passed/skipped/failed counts, the
state, and which optional reference implementations were detected on this machine.

Exit code 0 iff every step is PASS (or SKIP, without --strict).
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent            # genesis/
DERIV = ROOT / "derivatives"

# (label, working dir) — one pytest run per suite (each has its own local imports)
SUITES = [
    ("profiles   (rule postures declared == inventory == live engine)", DERIV / "profiles"),
    ("model      (script engine, sighash, checksig, instruments)", DERIV / "model"),
    ("p2p        (wire relay + chain sync)",                        DERIV / "p2p"),
    ("wallet     (SelectCoins / CreateTransaction)",               DERIV / "wallet"),
    ("persist    (CDiskBlockIndex save/reload)",                    DERIV / "persist"),
    ("conformance(6-chain matrix, every column execution-checked)", DERIV / "conformance"),
    ("crypto     (v0.1 ECDSA vs real libsecp256k1 — Thread A)",     DERIV / "crypto_conformance"),
    ("curve      (secp256k1 endomorphism / generator provenance / twist)", DERIV / "curve_structure"),
    ("hash       (SHA-256 NUMS constants / merkle 64-byte / RIPEMD margin)", DERIV / "hash_structure"),
    ("overflow   (v0.1 CheckTransaction vs the Aug-2010 MoneyRange fix)", DERIV / "overflow"),
    ("script_lim (v0.1 EvalScript has no element/op/stack ceilings)", DERIV / "script_limits"),
    ("retarget   (v0.1 GetNextWorkRequired fencepost + timewarp boundary)", DERIV / "retarget"),
    ("vectors    (language-neutral JSON corpus: export == committed, replays from the rules alone)", DERIV / "vectors"),
    ("temporal   (median-time-past, block timestamps, tx finality)", DERIV / "temporal"),
    ("emergent   (the BDB lock rule of 0.8.1 and BIP 66 DER, against the January side)", DERIV / "emergent"),
    ("origin_pol (replacement by nSequence, checkpoints, the fee rule: the origin against 2010)", DERIV / "origin_policy"),
    ("tracker    (origin-distance of each claimant over time)",      DERIV / "tracker"),
    ("nov08x     (NOV08 counterfactual + live network)",           DERIV / "nov08x"),
    ("jan09x     (released chain, full vocab + live network)",     DERIV / "jan09x"),
    ("ledger     (UTXO ConnectInputs/ConnectBlock; transacting)",   DERIV / "ledger"),
    ("market     (R6 commerce model: signatures + atoms reputation)", DERIV / "market"),
    ("studio     (R7 script debugger / stack tracer)",              DERIV / "studio"),
    ("console    (R7 capstone: full-stack driver on both X-chains)", DERIV / "console"),
    ("netnode    (Path B: hardened joinable node — TCP sync, checksums, persistence)", DERIV / "netnode"),
    ("dnsseed    (bootstrap DNS seed: crawl reachable nodes, answer A queries)",       DERIV / "dnsseed"),
]

# (label, script, dir, committed files the script rewrites) — regenerate a committed artifact and
# confirm the regenerated bytes are the committed bytes
ARTIFACTS = [
    ("descendant matrix  -> MATRIX.md / conformance.json", "conformance.py", DERIV / "conformance",
     ["MATRIX.md", "conformance.json"]),
    ("NOV08-X differential-> DIFFERENTIAL.md / PROVENANCE.json", "differential.py", DERIV / "nov08x",
     ["DIFFERENTIAL.md", "PROVENANCE.json"]),
    ("genesis recipe -> both laboratory genesis blocks re-derive from source", "verify_genesis.py", ROOT / "scripts",
     []),
]

CPP = [  # optional: C++/OpenSSL port differentials (bash run scripts)
    ("port  differential (MODEL == PORT interpreter)", DERIV / "port" / "run.sh"),
    ("node  ports (historical genesis re-derived + chain connect)", DERIV / "node" / "run.sh"),
]

# Optional reference implementations. A suite that needs one and does not find it SKIPS; the
# manifest records which were detected so a green run says what it compared against.
REFERENCES = {
    "python-bitcoinlib": "bitcoin",      # the Bitcoin Core rule set, for the descendant matrix
    "bitcoinx": "bitcoinx",              # BSV rules + libsecp256k1, for the matrix and the crypto thread
}

# `--core`: the consensus / script / value / ledger reconstruction core only. Excludes the neutral
# descendant tracker + conformance matrix (a separate comparison study), the UI tools, and the
# bootstrap seed — none of which are part of the reconstruction's own fidelity claims.
CORE_EXCLUDE_SUITES = {"conformance", "tracker", "console", "studio", "dnsseed"}
CORE_EXCLUDE_ARTIFACTS = {"conformance.py"}

PYTEST_SUMMARY = re.compile(r"(\d+) (passed|skipped|failed|error|errors|xfailed|xpassed|deselected)")


def detected_references() -> dict[str, bool]:
    return {name: importlib.util.find_spec(module) is not None for name, module in REFERENCES.items()}


def run(cmd, cwd) -> tuple[bool, str, str]:
    p = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)
    out = (p.stdout + p.stderr).strip()
    return p.returncode == 0, (out.splitlines()[-1] if out else ""), out


def run_pytest(py: str, d: Path) -> dict:
    """One pytest run, read for what it did rather than only whether it exited 0."""
    ok, tail, out = run([py, "-m", "pytest", "-q"], d)
    counts = {"passed": 0, "skipped": 0, "failed": 0}
    for n, kind in PYTEST_SUMMARY.findall(out.splitlines()[-1] if out else ""):
        if kind in counts:
            counts[kind] += int(n)
        elif kind in ("error", "errors"):
            counts["failed"] += int(n)
    if not ok or counts["failed"]:
        state = "FAIL"
    elif counts["passed"] == 0 and counts["skipped"] > 0:
        state = "SKIP"
    else:
        state = "PASS"
    return {"state": state, "tail": tail, **counts}


def run_artifact(py: str, script: str, d: Path, files: list[str]) -> dict:
    """Regenerate, compare against the committed bytes, restore the committed bytes, report."""
    before = {f: (d / f).read_bytes() if (d / f).exists() else None for f in files}
    ok, tail, _ = run([py, script], d)
    drift = []
    for f in files:
        after = (d / f).read_bytes() if (d / f).exists() else None
        if after != before[f]:
            drift.append(f)
            if before[f] is None:
                (d / f).unlink(missing_ok=True)
            else:
                (d / f).write_bytes(before[f])              # a run leaves the tree as it found it
    if not ok:
        return {"state": "FAIL", "tail": tail, "drift": drift}
    if drift:
        return {"state": "FAIL", "drift": drift,
                "tail": "regenerated bytes differ from the committed " + ", ".join(drift)
                        + " (committed bytes restored); a reference implementation may be missing -- see the manifest"}
    return {"state": "PASS", "tail": tail, "drift": []}


def _manifest(steps, args, refs, path) -> None:
    import datetime
    import json
    import platform
    ok_git, commit, _ = run(["git", "rev-parse", "HEAD"], ROOT)
    states = [s["state"] for _, s in steps]
    doc = {
        "schema": 2,
        "generated": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
        "commit": commit if ok_git else None,
        "core_only": args.core,
        "strict": args.strict,
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "backends": {"rust": args.rust, "cpp": args.cpp},
        "references_detected": refs,
        "steps": [{"step": lbl.split("(")[0].strip(), "state": s["state"],
                   "passed": s.get("passed"), "skipped": s.get("skipped"), "failed": s.get("failed"),
                   "artifact_drift": s.get("drift")} for lbl, s in steps],
        "pass": states.count("PASS"), "skip": states.count("SKIP"), "fail": states.count("FAIL"),
        "total": len(steps),
        "all_passed": all(st == "PASS" for st in states),
        "green": all(st != "FAIL" for st in states) and (not args.strict or "SKIP" not in states),
    }
    path.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    print(f"manifest -> {path.name} (PASS {doc['pass']}  SKIP {doc['skip']}  FAIL {doc['fail']}, commit {(commit or '?')[:12]})")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rust", action="store_true", help="also run the Rust node suite (needs cargo)")
    ap.add_argument("--cpp", action="store_true", help="also run the C++ port differentials (needs g++ and OpenSSL headers)")
    ap.add_argument("--core", action="store_true",
                    help="run only the consensus/script/value/ledger reconstruction core (excludes the "
                         "descendant tracker + conformance matrix, UI tools, and bootstrap seed); "
                         "writes a machine-readable results manifest")
    ap.add_argument("--strict", action="store_true",
                    help="a suite that only skipped, or a reference implementation that is not installed, fails the run")
    ap.add_argument("--manifest", type=Path, default=None,
                    help="write a results manifest to this path (implied by --core)")
    args = ap.parse_args()
    py = sys.executable
    steps: list[tuple[str, dict]] = []

    def _first_word(label: str) -> str:                  # "conformance(6-chain ...)" -> "conformance"
        return label.split("(")[0].split()[0]

    def show(label: str, s: dict) -> None:
        counts = ""
        if "passed" in s:
            counts = f"{s['passed']} passed, {s['skipped']} skipped, {s['failed']} failed"
        print(f"  [{s['state']}] {label:60} {counts or s.get('tail', '')}")
        if s["state"] != "PASS" and counts and s.get("tail"):
            print(f"         {s['tail']}")

    suites, artifacts = SUITES, ARTIFACTS
    if args.core:
        suites = [(l, d) for (l, d) in SUITES if _first_word(l) not in CORE_EXCLUDE_SUITES]
        artifacts = [(l, s, d, f) for (l, s, d, f) in ARTIFACTS if s not in CORE_EXCLUDE_ARTIFACTS]

    refs = detected_references()
    print("== reference implementations detected: "
          + ", ".join(f"{k}={'yes' if v else 'no'}" for k, v in refs.items()) + " ==")
    if args.strict and not all(refs.values()):
        missing = [k for k, v in refs.items() if not v]
        print(f"  [FAIL] {'reference implementations':60} not installed: {', '.join(missing)} "
              f"(pip install -e '.[refs]')")
        steps.append(("reference implementations", {"state": "FAIL", "tail": "missing: " + ", ".join(missing)}))

    print(f"== derivatives test suites{' (core)' if args.core else ''} ==")
    for label, d in suites:
        s = run_pytest(py, d)
        steps.append((label, s))
        show(label, s)

    print("== regenerate derived artifacts (compared to the committed bytes; the tree is restored) ==")
    for label, script, d, files in artifacts:
        s = run_artifact(py, script, d, files)
        steps.append((label, s))
        show(label, s)

    if args.rust:
        print("== Rust node (validator-rs) ==")
        cargo = shutil.which("cargo")
        rs_dir = DERIV / "validator-rs"
        if not cargo or not rs_dir.exists():
            s = {"state": "FAIL", "tail": "cargo/crate unavailable (--rust was requested)"}
        else:
            ok, tail, _ = run([cargo, "test", "--locked", "--quiet"], rs_dir)
            s = {"state": "PASS" if ok else "FAIL", "tail": "all Rust suites passed" if ok else tail}
        steps.append(("validator-rs (cargo test)", s))
        show("validator-rs (cargo test)", s)

    if args.cpp:
        print("== C++/OpenSSL port differentials ==")
        bash = shutil.which("bash")
        for label, script in CPP:
            if not bash or not script.exists():
                s = {"state": "FAIL", "tail": "bash/script unavailable (--cpp was requested)"}
            else:
                ok, tail, _ = run([bash, str(script)], script.parent)
                s = {"state": "PASS" if ok else "FAIL", "tail": tail}
            steps.append((label, s))
            show(label, s)

    states = [s["state"] for _, s in steps]
    n_pass, n_skip, n_fail = states.count("PASS"), states.count("SKIP"), states.count("FAIL")
    green = n_fail == 0 and (not args.strict or n_skip == 0)
    verdict = "ALL PASSED" if (green and n_skip == 0) else ("GREEN WITH SKIPS" if green else "FAILURES ABOVE")
    print(f"\n{verdict} — PASS {n_pass}  SKIP {n_skip}  FAIL {n_fail}  of {len(steps)} steps."
          + ("" if n_skip == 0 else " A SKIP step checked nothing: install the missing reference "
                                    "implementation (pip install -e '.[refs]') or run with --strict to make it fail."))
    if args.core or args.manifest:
        _manifest(steps, args, refs, args.manifest or (ROOT / "reproduce-manifest.json"))
    return 0 if green else 1


if __name__ == "__main__":
    raise SystemExit(main())
